version: "3"
services:
  nginx:
    image: nginx
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./v2ray/v2ray.conf:/etc/nginx/v2ray.conf:ro
      - ./v2ray/data:/data
      - ./logs/:/var/log/nginx
      - ./favlink.cn.key:/etc/nginx/cert/favlink.cn.key:ro
      - ./favlink.cn.pem:/etc/nginx/cert/favlink.cn.pem:ro
      - ./zhangjh.me.key:/etc/nginx/cert/zhangjh.me.key:ro
      - ./zhangjh.me.pem:/etc/nginx/cert/zhangjh.me.pem:ro
      - ./translate.favlink.cn.key:/etc/nginx/cert/translate.favlink.cn.key:ro
      - ./translate.favlink.cn.pem:/etc/nginx/cert/translate.favlink.cn.pem:ro
    environment:
      TZ: Asia/Shanghai
    ports:
      - 80:80
      - 443:443
