version: "3"
services:
  mysql:
    build:
      context: .
      dockerfile: Dockerfile_mysql
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: zhangjh
      MARIADB_DATABASE: nextcloud
      MARIADB_USERNAME: nextcloud
      MARIADB_PASSWORD: zhangjh
    ports:
      - 3306:3306
    volumes:
      - /app/nextcloud/mysql:/var/lib/mysql
        #onlyoffice:
   #image: onlyoffice/documentserver
   #build:
   #   context: .
   #   dockerfile: Dockerfile_onlyoffice
   # restart: always
   # ports:
   #   - 9000:80
   # volumes:
   #   - /app/onlyoffice/logs:/var/log/onlyoffice
   #   - /app/onlyoffice/data:/var/www/onlyoffice/data
  nextcloud:
    build:
      context: .
      dockerfile: Dockerfile_nextcloud
    depends_on:
      - mysql
        #- onlyoffice
    restart: always
    ports:
      - 8081:80
        #privileged: true
    volumes:
      - /app/nextcloud/data:/var/www/html
      - /mnt/share:/mnt/share
    links:
      - mysql
        #- onlyoffice
