FROM nextcloud

WORKDIR ./

#RUN sed -i "s@http://deb.debian.org@http://mirrors.aliyun.com@g" /etc/apt/sources.list
#RUN echo "deb https://mirrors.ustc.edu.cn/ubuntu/ jammy main restricted universe multiverse" > /etc/apt/sources.list
#RUN cat /etc/apt/sources.list
#RUN rm -Rf /var/lib/apt/lists/*
#RUN apt-get clean
#RUN apt-get update
#RUN apt-get -y install vim smbclient libsmbclient-dev && pecl install smbclient && docker-php-ext-enable smbclient
#RUN apt-get -y install libmagickcore-6.q16-6-extra
