version: "3"
services:
  base:
    build:
      context: ./
      dockerfile: Dockerfile_base
  qbit:
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
      - WEBUI_PORT=8088
    volumes:
      - /home/zhangjh/qb/appdata/config:/config
      - /mnt/nas/下载:/downloads
    ports:
      - 8088:8088
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped

  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: zhangjh
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD: zhangjh
    ports:
      - 3306:3306
    volumes:
      - /app/nextcloud/mysql:/var/lib/mysql
  nextcloud:
    build:
      context: .
      dockerfile: Dockerfile_nextcloud
    depends_on:
      - mysql
    restart: always
    ports:
      - 8081:80
    volumes:
      - /app/nextcloud/data:/var/www/html
      - /mnt/nas:/mnt/nas
    links:
      - mysql
