version: "3"
services:
    frpc_nas:
        image: snowdreamtech/frpc
        restart: always
        network_mode: host
        container_name: frpc_nas
        volumes:
             - ./frpc_nas.ini:/etc/frp/frpc.ini
    frpc_favlink:
        image: snowdreamtech/frpc
        restart: always
        network_mode: host
        container_name: frpc_favlink
        volumes:
             - ./frpc_favlink.ini:/etc/frp/frpc.ini
    frpc_comment:
        image: snowdreamtech/frpc
        restart: always
        network_mode: host
        container_name: frpc_web
        volumes:
             - ./frpc_web.ini:/etc/frp/frpc.ini
    frpc_blog:
        image: snowdreamtech/frpc
        restart: always
        network_mode: host
        container_name: frpc_blog
        volumes:
             - ./frpc_blog.ini:/etc/frp/frpc.ini
    frpc_ssh:
        image: snowdreamtech/frpc
        restart: always
        network_mode: host
        container_name: frpc_ssh
        volumes:
             - ./frpc_ssh.ini:/etc/frp/frpc.ini
