version: "3"
services:
      #mongo:
      #build: 
      #context: .
      #dockerfile: Dockerfile_mongo
      #environment:
      #  MONGO_INITDB_ROOT_USERNAME: root
      #  MONGO_INITDB_ROOT_PASSWORD: zhangjh
  frpc:
    image: snowdreamtech/frpc
    container_name: frpc
    network_mode: host
    restart: always
    volumes:
      - ./frpc/frpc_favlink.ini:/etc/frp/frpc_favlink.ini
      - ./frpc/frpc_comment.ini:/etc/frp/frpc_comment.ini
      - ./frpc/frpc_nas.ini:/etc/frp/frpc_nas.ini
      - ./frpc/frpc_qt.ini:/etc/frp/frpc_qt.ini
  comment:
    container_name: comment
    network_mode: host
    build: 
      context: ./comment
      dockerfile: ./Dockerfile
    restart: always
  favlink:
    container_name: favlink
    network_mode: host
    build: 
      context: ./favlink
      dockerfile: ./Dockerfile
    restart: always
      #blog:
      #container_name: blog
      #network_mode: host
      #build: ./blog
      #restart: always
      #ports: 
      #- 3000:3000
      #- 3001:3001
      #- 4000:4000
        #depends_on: mongo
      #favlink:
      #build:
      #context: .
      #dockerfile: Dockerfile_favlink
      #restart: always
      #ports:
      #- 3000:3000
      #depends_on:
      #- mongo
