### 自动部署MongoDB、favlinks、comment、blog的docker-compose文件
### 其中各应用的镜像已推送docker hub，如有变动会在每次push时自动由action生成新的镜像推送
version: "3"
services:
  mongo:
    image: mongo:4.2.22
    container_name: mongo
    network_mode: host
    restart: always
    environment:
    - TZ=Asia/Shanghai
    volumes:
      - /mnt/nas/dev/mongodb/data:/mongo/data
      - /mnt/nas/dev/mongodb/log:/mongo/log
    command:
      - bash
      - -c
      - mongod --port 20172 --bind_ip_all --dbpath /mongo/data --logpath /mongo/log/mongo.log

  comment:
    container_name: comment
    image: njhxzhangjh/comment
    restart: always
    network_mode: host
    logging:
      driver: "json-file"
      options:
        max-size: "200m"
    depends_on:
      - mongo

  favlinks:
    container_name: favlinks
    image: njhxzhangjh/favlinks
    restart: always
    network_mode: host
    logging:
      driver: "json-file"
      options:
        max-size: "200m"
    depends_on:
      - mongo
    volumes:
      - ./favlinks/conf:/favlinks/conf
        #command:
        #- bash 
        #- -c
        #- ls /favlinks/views

  blog:
    container_name: blog
    image: njhxzhangjh/blog
    restart: always
    network_mode: host
    logging:
      driver: "json-file"
      options:
        max-size: "200m" 
    depends_on:
      - comment
      
  translation:
    container_name: translation
    image: njhxzhangjh/translation
    restart: always
    network_mode: host
    logging:
      driver: "json-file"
      options:
        max-size: "200m" 
